print("###########################################################################")
print("")
print("# Author: Jude Ragudo")
print("")
print("# Date: January 27, 2020")
print("")
print("# Course: LBYCPA1")
print("")
print("# Program Description:")
print("# My program is an online ordering service called 'Summer Cravings'.")
print("# A customer will be given two choices. The order choices are either [1] Halo-Halo or [2] Mais Con Yelo.")
print("# If they don't want to order, there is an exit option [X].")
print("# After typing the assigned number of their order choice, the price of the order will be shown.")
print("# Afterwards, the customer should have chosen their order and its corresponding price.")
print("")
print("###########################################################################")